### ISSUE TITLE
Bug in auto-completer after upgrading Prototype to 1.7.1

### ISSUE THREAD

**Issue by sebastfr** [eprints/eprints#130]
From Dennis / EP-Tech

Yep, it pops up at the top of the page. A bit of trying different
scroll positions shows that it probably shows up with the relative
distance between the control and the top of the window added to the
start of the page instead of the top of the window.

---

I found the solution:

In 70_autocomplete.js, you need to replace:
Position.clone( ...

With:
Element.clonePosition(...

Position is deprecated in Prototype. Somehow these 2 behave differently now.

**Comment by vedranvucic** [comment]
What is path to the file that should be patched?  I use Eprints 3.3.15.
Thanks
