### ISSUE TITLE
metadata_visibility not being reset

### ISSUE THREAD

**Issue by sebastfr** [eprints/eprints#131]
(test if still relevant in 3.3.12)

From Alan Stiles on EP-tech:

Not sure if anyone else has seen this or if it has already been flagged previously (quick search didn’t give me any likely results):

In the situation where an item is replaced by a new version, EPrints sets the metadata_visibility flag on the original item to “no_search” so it won’t appear in search results (or view builds?).

If however, the new item is subsequently deleted from EPrints, the flag is not reset to “show” on the original item to make it visible once more, resulting in items being in the repository, but essentially undiscoverable?

I’ve manually fixed the metadata_visibility flag against these ‘orphaned’ items via SQL, but have I missed the obvious admin interface function to fix it, or have I misunderstood something fundamental and am now merrily corrupting our system?

**Comment by wfyson** [comment]
Fixed with https://github.com/eprints/eprints/commit/b059e0ddd6d196059f14986cb532e3db7cebf84c
