### ISSUE TITLE
localtime insteed of utc

### ISSUE THREAD

**Issue by cmdtstof** [eprints/eprints#174]
time (of diverse objects) is showing in utc insteed of localtime.

time  in eprints should be rendered in localtime.

scince there is no comment on http://www.eprints.org/tech.php/18356.html
i add this bug as an issue here.
there is not a big different UTC to localtime in europe (more in amerika/asia), but this could lead to confusing and isn't whats documented under http://wiki.eprints.org/w/Time_field.

thanks

**Comment by jiadiyao** [comment]
See #194
