### ISSUE TITLE
Update creative commons licensing options to v4 and retain version info when licences are granted

### ISSUE THREAD

**Issue by jesusbagpuss** [eprints/eprints#183]
Currently, eprints only stores the licence type (e.g. cc_by_nd), but not the version of the license.

Should the options be updated to:
cc_by_nc_4.0
or use the URI of the license instead?

There is also a mismatch in the versions offered (in the workflow) and the rendering of them on a summary page.
https://github.com/eprints/eprints/blob/master/lib/lang/en/phrases/system.xml#L3259

```
<epp:phrase id="licenses_typename_cc_by_nd">Creative Commons: Attribution-No Derivative Works 3.0</epp:phrase>
```

the description (rendered on an abstract page) is 2.5:

```
<epp:phrase id="licenses_description_cc_by_nd"><a href="http://creativecommons.org/licenses/by-nd/2.5/">Creative Commons Attribution No Derivatives</a></epp:phrase>
```

RDF triples use 3.0 licences:
https://github.com/eprints/eprints/blob/master/lib/cfg.d/rdf_triples_eprints.pl

I'm happy to code whatever the solution should be - but I'm not sure what the best way forward is (looking at the 'contributors' namedset, I'm thinking that URIs might be best)?

**Comment by photomedia** [comment]
A mismatch of the label and the pointer to the license is unacceptable, it is not an enhancement, but a bug.  The user is offered option to select version "3.0" of a license, but the link shown on the abstract page points to a "2.5" license.  These types of bugs should be fixed quickly please.

**Comment by icklecows** [comment]
This has already been fixed in branch 3.3, which has superseded branch master since this was raised as an issue:

https://github.com/eprints/eprints/blob/3.3/lib/lang/en/phrases/system.xml#L3305

**Comment by photomedia** [comment]
Good news, thanks for the clarification!  Which version of EPrints was this bug fixed in ?

**Comment by icklecows** [comment]
Looks to me like 3.3.13 (early 2015).  It seems to have been fixed in response to a duplicate bug report #127 (which also seems to still be open).  I think this issue and issue 127 should both be closed to avoid further confusion.

**Comment by photomedia** [comment]
Thank you!

**Comment by wfyson** [comment]
Thanks for flagging this up!
