### ISSUE TITLE
Lightbox popup - imageDataContainer not shown in IE9

### ISSUE THREAD

**Issue by drtjmb** [eprints/eprints#199]
Observed in IE9 - when a preview is displayed using the "lightbox" mechanism the information below the image (eg. Next, Prev buttons, image description, Close button) does not appear and the "lightbox" has to be closed by pressing the escape key.

Works ok in IE8.

**Comment by phluid61** [comment]
Have we solved this by doing nothing for two years? (Do we still support IE9, since even MS doesn't?)

**Comment by jiadiyao** [comment]
IE9 no longer supported.
