### ISSUE TITLE
Changes in Apache 2.4 / mod_perl (remote IP)

### ISSUE THREAD

**Issue by sebastfr** [eprints/eprints#214]
Reported by David McElroy on ep-tech.

See http://www.marshut.com/ippzhs/problem-with-apache2-connection-remote-ip.html and http://httpd.apache.org/docs/2.4/developer/new_api_2_4.html (search for "remote_ip").

conn_rec->remote_ip and conn_rec->remote_addr
    These fields have been renamed in order to distinguish between the client IP address of the connection and the useragent IP address of the request (potentially overridden by a load balancer or proxy). References to either of these fields must be updated with one of the following options, as appropriate for the module:

```
    When you require the IP address of the user agent, which might be connected directly to the server, or might optionally be separated from the server by a transparent load balancer or proxy, use request_rec->useragent_ip and request_rec->useragent_addr.
    When you require the IP address of the client that is connected directly to the server, which might be the useragent or might be the load balancer or proxy itself, use conn_rec->client_ip and conn_rec->client_addr.
```

**Comment by denics** [comment]
Short answer tested on eprints 3.3.12:
Edit file 
```
/perl_lib/EPrints/DataObj/LoginTicket.pm
```
change

```
143         my $ip = $r->connection->remote_ip;
```

with

```
143         my $ip = $r->connection->client_ip;
```
