### ISSUE TITLE
Disallow robot access to https cgi 

### ISSUE THREAD

**Issue by MrkGrgsn** [eprints/eprints#238]
robots.txt disallows /cgi/ but the same URLs can be accessed over https under some configurations at least, e.g., on our server it is /cgi/ and /secure/cgi/.

**Comment by jiadiyao** [comment]
robots.txt is written by perl_lib/EPrints/Apache/RobotsTxt.pm
How did you setup your /secure/cgi  path?

**Comment by phluid61** [comment]
(I've inherited QUT ePrints from @MrkGrgsn) I think this is old enough that it's been completely superseded. Our path config has been completely rewritten since then, and our robots.txt seems find these days.

**Comment by MrkGrgsn** [comment]
As @phluid61 says I stopped working on this years ago and I can't recall how it was configured. I guess the crux of the request is that robot exclusions for `/cgi/` are hardcoded in robots.txt https://github.com/eprints/eprints/blob/3.3/perl_lib/EPrints/Apache/RobotsTxt.pm#L45-L48. The secure cgi equivalent, if such a thing still exists, is not blocked.

**Comment by phluid61** [comment]
Oh wow, I hadn't seen that. Definitely a fixer-upper.
