### ISSUE TITLE
Views.pm : max_items bug

### ISSUE THREAD

**Issue by mpbraendle** [eprints/eprints#259]
perl_lib/EPrints/Update/Views.pm , around line 536:

`# hit the limit`
`if ($count == $max_items+1)`

results in a warning message if max_items is 0 (which means disabled max items limitation) and there is exactly 1 item in the view. Hence, the user cannot have a look at the item. In addition, comparing on equality is wrong here.

A possible bug fix is as follows:

`+        # UZH CHANGE fixed bug, 2014/08/06/mb`
`+		 # if ($count == $max_items+1)`
`+		 if ($count > $max_items && $max_items != 0)`
` 		 {`
` 		 		 my $PAGE = $xml->create_element( "div",`
`		 		 		 class => "ep_view_page ep_view_page_view_$view->{id}"`

**Comment by patrickmcsweeney** [comment]
fixed by 93921882b6f756c4469b85b87b438fa3a1a2e1c7
