### ISSUE TITLE
EPrints dies with unhelpful error message if Time::HiRes is not installed

### ISSUE THREAD

**Issue by MrkGrgsn** [eprints/eprints#265]
If `Time::HiRes` is not installed EPrints fails with a rather obtuse error message:

> $ bin/epadmin 
> Undefined subroutine &EPrints::SystemSettings::load_config_file called at /eprints/eprints/eprints-core/bin/../perl_lib/EPrints/Config.pm line 150.
> Compilation failed in require at bin/epadmin line 250.
> BEGIN failed--compilation aborted at bin/epadmin line 250.

`Time::HiRes` is used within an eval in `EPrints::Config::_bootstrap()` which injects  `load_config_file()` into `EPrints::SystemSettings` so the call on line 150 fails.

Removing the `use Time::HiRes;` line allows EPrints to run and it's not clear to me why it's required at all.

**Comment by jiadiyao** [comment]
fixed https://github.com/eprints/eprints/commit/12d2b197bf5f03cef536c649534b5b91a95d2f1c
