### ISSUE TITLE
Corrupted revision XML file after copy-pasting ligatures

### ISSUE THREAD

**Issue by jploski** [eprints/eprints#269]
Reporting against EPrints 3.3.12: if a user pastes an abstract from a PDF file which does not contain properly (?) encoded ligatures (which for us happens regularly), not only does the pasted text display unlegible characters, those characters are apparently also written to the revision XML file, breaking the expected UTF-8 encoding and creating malformed XML. For example, instead of the fi ligature in the word "significantly", the byte 0x0c is output:

```
0000000: 7369 676e 690c 6361 6e74 6c79 0a         signi.cantly.
```

The malformed XML of the revision file in turn causes Internal Server Error when trying to browse the history of edits. So we have a DoS situation due to injection of invalid content - this could be even classified as a (minor) security issue.

For further discussion of ligatures encoding in PDF, see: http://tex.stackexchange.com/questions/86614/can-we-make-ligatures-copy-and-pastable)

**Comment by drn05r** [comment]
I am unsure why characters \x80-\x9f need to be replaced as these do not cause my XML to become invalid when they are used.  Although some of the characters cannot be rendered and in my history tab appear as rectangular boxes.

I would suggest the regex:

$data =~ s/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f/\x{fffd}/g;
