### ISSUE TITLE
Upload progress bar generating error in IE 11

### ISSUE THREAD

**Issue by icklecows** [eprints/eprints#287]
The upload progress bar is generating an error message in IE 11 - this appears to be because it is generating an additional upload progress bar which then (not sure which here) either generates an additional uuid or tries to use the uuid for the successful upload which no longer has outstanding progress?

I was able to replicate the error on demoprints so it doesn't seem to relate to any plugins.

At University of Bath and on Demoprints, the file does seem to upload - not sure if this is the case for Queen Margaret University.

![demoprints](https://cloud.githubusercontent.com/assets/7404917/5375583/b21c376c-8063-11e4-910c-135877dad5a4.png)

**Comment by msharifi68** [comment]
hi dear jiadiyao
i install eprints 3.3.15 and get same error that writed by icklecows
i read issue **ee59097** and checked 88_uploadmethod_file.js file.
line 252 and 350 is correct
but i get error in any Browser
