### ISSUE TITLE
Error code language for multilang data after update

### ISSUE THREAD

**Issue by alexukua** [eprints/eprints#289]
Hi 

After update Eprints from 3.2.x to 3.3.12 language  code  is not correct 

![eprints_bug](https://cloud.githubusercontent.com/assets/2523023/5571568/11257c9a-8f9c-11e4-8224-0eb83fe8881b.png)

Do you have any idea about how to fix this bug?

**Comment by jiadiyao** [comment]
I am not sure if I understand your problem.

If you want to add additional language to the drop down, you can add the language code to 
/opt/eprints3/archives/[archive ID]/namedsets/language
then add the appropriate phrase.

**Comment by patrickmcsweeney** [comment]
I think issue is there are two items in the list pull down which are unspecified. But one is actually unspecified and one should be the repository default language

**Comment by alexukua** [comment]
This a problem was linking with a configuration Eprints. After normalization all codes language  in config Eprints this problem  declined.
