### ISSUE TITLE
toform functions don't get all parameters

### ISSUE THREAD

**Issue by Ainmhidh** [eprints/eprints#302]
The documentation at http://wiki.eprints.org/w/Category:EPrints_Metadata_Fields suggests calls to 'toform' get 4 parameters ($value, $session, $object, $basename), but the call in EPrints::MetaField::render_input_field only passes $value and $session.
fromform calls have all 4 parameters passed, so it seems sensible to pass all 4 to toform functions.

**Comment by Ainmhidh** [comment]
I'll attempt to make the simple change for this.

**Comment by jesusbagpuss** [comment]
Fixed  by #303
