### ISSUE TITLE
Sanitise doesn't include spaces to underscores

### ISSUE THREAD

**Issue by icklecows** [eprints/eprints#323]
eprints/perl_lib/EPrints/System.pm doesn't sanitise spaces to underscores.

Could we update line 544 (branch 3.3 - it's 626 in Master...) from:
$filepath =~ s![\x00-\x0f\x7f<>:"\|?*]!_!g;

to:

 $filepath =~ s![\x00-\x0f\x7f\x20<>:"\|?*]!_!g;

to catch spaces too?

Lizz

**Comment by jiadiyao** [comment]
#381: adding local config: optional_filename_sanitise.pl

**Comment by jiadiyao** [comment]
Additional sanitisation can be added in the local optional_filename_sanitise.pl config in the next release (v3.3.16) #381, #380.
