### ISSUE TITLE
Bug in the computed SQL of the title_duplicates script (3.3.14)

### ISSUE THREAD

**Issue by mamalos** [eprints/eprints#348]
I have mentioned this bug in eprints-tech list.

In the conditional of line 73 (on Debian, Eprints 3.3.14) of the specific script, as one can see, if $dataset_name neq "eprint", then the SQL WHERE statement is immediately followed by an AND statement, which would cause SQL to fail.

An easy workaround for this bug is presented in this patch (where the AND statement is moved inside the body of conditional):

--- a/cgi/users/lookup/title_duplicates    2015-04-17 19:07:54.000000000 +0300
+++ b/cgi/users/lookup/title_duplicates    2015-09-30 10:45:40.510270944 +0300
@@ -71,9 +71,9 @@
     " FROM $Q_table" .
     " WHERE ";
 if ($dataset_name eq "eprint") {
-    $sql .= " $Q_eprint_status=" .  $db->quote_value( "archive" );
+    $sql .= " $Q_eprint_status=" .  $db->quote_value( "archive" ) . " AND ";
 }
-$sql .=    " AND $Q_id!=$id" .
+$sql .=    "$Q_id!=$id" .
     " AND $Q_field_name IS NOT NULL" .
     " AND $Q_field_name " .
     $db->sql_LIKE() .

**Comment by denics** [comment]
Hei @mamalos , thanks for spotting this, can you make a pull request with your modification? otherwise the patch looks a bit weird!
Thanks

**Comment by mamalos** [comment]
Hi denics,

I'm not sure I understood you. You want me to make a pull request to do what exactly? You mean you want me to submit the output of a git diff (between the corrected version and the previous) as a patch?

**Comment by mamalos** [comment]
OK, I didn't do the pull request, but rather enclosed my patch within a code block. Is it OK with you now?

Proposed patch:

<pre><code>
--- a/cgi/users/lookup/title_duplicates Wed Sep 30 11:35:27 2015 +0300
+++ b/cgi/users/lookup/title_duplicates Fri Oct 02 13:26:25 2015 +0300
@@ -71,9 +71,9 @@
        " FROM $Q_table" .
        " WHERE ";
 if ($dataset_name eq "eprint") {
-       $sql .= " $Q_eprint_status=" .  $db->quote_value( "archive" );
+       $sql .= " $Q_eprint_status=" .  $db->quote_value( "archive" ) . " AND ";
 } 
-$sql .=        " AND $Q_id!=$id" .
+$sql .=        " $Q_id!=$id" .
        " AND $Q_field_name IS NOT NULL" .
        " AND $Q_field_name " .
        $db->sql_LIKE() .
</code></pre>

**Comment by denics** [comment]
thanks, much better! I will try it right now.
