### ISSUE TITLE
epindexer not working in Debian installation of EPrints 3.3.14 due to missing dependency

### ISSUE THREAD

**Issue by mamalos** [eprints/eprints#350]
As I've already mentioned in eprints-tech list (http://www.eprints.org/tech.php/20801.html), there's a problem with epindexer in Debian which prohibits it from starting due to a missing dependency (specifically Config/General.pm). The missing dependency package is libconfig-general-perl. When installed, the daemon starts as expected.

The way I discovered the problem and then resolved it follows (just for reproducing purposes):

<pre>

# systemctl status epindexer.service -l

epindexer.service - SYSV: Start the eprints indexer daemon as the correct user
   Loaded: loaded (/etc/init.d/epindexer)
   Active: failed (Result: exit-code) since Wed 2015-10-07 16:42:25 EEST; 2min 36s ago
  Process: 6517 ExecStart=/etc/init.d/epindexer start (code=exited, status=2)
Oct 07 16:42:25 pamak-e-prints epindexer[6517]: Can't locate Config/General.pm in @INC (you may need to install the Config::General module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl) at /etc/init.d/epindexer line 17.
Oct 07 16:42:25 pamak-e-prints epindexer[6517]: BEGIN failed--compilation aborted at /etc/init.d/epindexer line 17.
Oct 07 16:42:25 pamak-e-prints systemd[1]: epindexer.service: control process exited, code=exited status=2
Oct 07 16:42:25 pamak-e-prints systemd[1]: Failed to start SYSV: Start the eprints indexer daemon as the correct user.
Oct 07 16:42:25 pamak-e-prints systemd[1]: Unit epindexer.service entered failed state.

# apt-get install libconfig-general-perl
# service epindexer start
# service epindexer status
 
epindexer.service - SYSV: Start the eprints indexer daemon as the correct user
   Loaded: loaded (/etc/init.d/epindexer)
   Active: active (running) since Wed 2015-10-07 16:50:43 EEST; 11s ago
  Process: 7841 ExecStart=/etc/init.d/epindexer start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/epindexer.service
           ├─7843 indexer
           ├─7844 indexer
           ├─7846 /bin/cat
           ├─7901 sh -c \/usr\/bin\/pdftotext -enc UTF-8 -layout \/usr\/share\/eprints3\/archives\/testpamak1\/documents\/disk0\/00\/00\/0...
           └─7902 /usr/bin/pdftotext -enc UTF-8 -layout /usr/share/eprints3/archives/testpamak1/documents/disk0/00/00/02/47/01/of_daemons_...

Oct 07 16:50:43 pamak-e-prints epindexer[7841]: Starting EPrints Indexer:                                  [  OK  ]
</pre>

**Comment by jesusbagpuss** [comment]
I know nothing about building Debian packages, but I'm guessing a fix would require adding
```
libconfig-general-perl
```
to a list of requirements somewhere...
Does this:
https://github.com/eprints/eprints/blob/3.3/eprints.spec.in
control what is output here:
https://github.com/eprints/eprints/blob/3.3/debian/control#L13
?

**Comment by sebastfr** [comment]
Check if the module is used first:

# Read the configuration file
my $confname = "$prefix/cfg/epindexer.conf";
my %conf;
if ( -f $confname )
{
	%conf = ParseConfig( $confname );
}

cfg/epindexer.conf ? I haven't done eprints for ages but i don't recall there was such a file. Could be wrong though.

**Comment by mamalos** [comment]
I also know nothing about building Debian packages, but I think that @jesusbagpuss solution would work (adding libconfig-general-perl in package's Depends list).

@sebastfr : I think that epindexer is sort of "mandatory", since if nothing is reindexed when making a change to the repository, then the repository's search capabilities are practically useless. So in that sense, I think that libconfig-general-perl should be added in EPrints' list of depending packages (for all distributions). Nonetheless, adding some code such the one you're suggesting would make the installation more robust.

**Comment by sebastfr** [comment]
Yeah i know that the indexer is needed hehehe :-) What i said is that i don't think the dependency you guys want to add to the list of dependencies is actually needed. So my suggestion is to remove the module from Eprints altogether. The module is called Config::General.

**Comment by mamalos** [comment]
@sebastfr, The file you're mentioning does not exist in my installation either. But this doesn't necessarily mean that it cannot exist if the user chooses so. From the code (https://github.com/eprintsug/ulcc-core/blob/master/bin/epindexer.in), one can see that $conf is later used in many places, which means that it is an optional file that allows admins to reconfigure certain parts of the indexer (logging, verbosity level, etc). If the same configuration parameters can be passed using a different way, then you're right, the plugin is not needed, but looking at the specific code, I don't see an alternative. So, I think Config::General is indeed needed and it should be added as a dependency.

Ah, and as I mentioned previously, I'm not sure if this dependency exists in the other Linux distro's as well...

**Comment by sebastfr** [comment]
That feature seems fairly undocumented. what's the format of the conf file (rhetorical question)? EPrints can parse PERL conf as done by EPrints::Config. If i were you (the eprints community), i'd adapt epindexer.in to use the EPrints config parsing functions rather than add an external dependency.

Now the decision lays in your hands :-)

**Comment by goetzk** [comment]
I just encountered this too, in my case via the init script on my local system which turns out to be a copy of bin/epindexer

https://github.com/eprints/eprints/blob/3.3/eprints.spec.in#L82

As far as I can tell epindexer has the only use of Config::General in eprints.
```
-bash-4.1$ grep -r 'Config::General' -is bin/ lib/ perl_* cfg/ cgi/ customscripts/ 
bin/epindexer:use Config::General qw( ParseConfig );
```

The commit adding that code doesn't explain why they went with a brand new dependency rather than eprints internal code.

https://github.com/eprints/eprints/commit/8fefac34c576e4aa96e4a8a385c6999485ec0b69
