### ISSUE TITLE
`bin/epadmin schema` depends on non-extant `Export::XML_Schema` plugin

### ISSUE THREAD

**Issue by phluid61** [eprints/eprints#378]
The `schema` action in the `epadmin` script attempts to load and execute the `Export::XML_Schema` plugin, which doesn't exist.

We should either add the plugin, or delete the action.

**Comment by drn05r** [comment]
XML Schema can be exported from the web interface at /cgi/schema.  Ideally this would use an Export::XML_Schema plugin which could then also be used in epadmin.  However, as it does not and as there is a way to do the equivalent to the command line option, the most straightforward thing to do is remove the option from epadmin.
