### ISSUE TITLE
Upload by URL floods /tmp

### ISSUE THREAD

**Issue by mpbraendle** [eprints/eprints#427]
The Upload by URL method floods /tmp , the process never stops.

Temporary workaround: Deactivate by setting a configuration in cfg.d/plugins.pl:
$c->{plugins}->{"Screen::EPrint::UploadMethod::URL"}->{params}->{disable} = 1;

**Comment by jesusbagpuss** [comment]
This issue is probably relevant: #102

**Comment by drn05r** [comment]
I have amended for a repository I support so it only includes the URL uploaded and anything directly linked from this URL.  This should incorporate any images, CSS and Javascript.  I will look at porting this into the core codebase
