### ISSUE TITLE
Screen::BatchEdit plugin cannot display radio list properly

### ISSUE THREAD

**Issue by phluid61** [eprints/eprints#428]
Our 'eprint' data object has a 'contributors' multi-valued compound field which includes a boolean sub-field "is_qut" which is displayed as a radio list:

```perl
{
  name => 'contributors',
  # ...
  fields => [
    # ...
    {
      sub_name => 'is_qut',
      type => 'boolean',
      input_style => 'radio',
    },
    # ...
  ],
  # ...
}
```

When performing a batch edit using `EPrints::Plugins::Screen::BatchEdit` it is possible to select the contributor field, which populates a table of actions×fields. However the "is_qut" column is filled with missing phrases that look like:

```
	["eprint_radio_fcd7e5a0-25b0-4440-b82e-7315db102db4_creators_is_qut" not defined
false ○

true ○

]
○ UNSPECIFIED
```

`EPrints::MetaField::Boolean::get_basic_input_elements` uses the following code to fill out the bulk of the radio list:

```perl
123:			$session->html_phrase(
124:				$self->{confid}."_radio_".$self->{name},
125:				true=>$true,
126:				false=>$false ) );
```

\[[src](https://github.com/eprints/eprints/blob/3.3/perl_lib/EPrints/MetaField/Boolean.pm#L123-L126)]

It appears the Boolean MetaField being rendered is actually that of the Search object, not the DataObj, so it gets a dynamically generated `confid`.

**Comment by phluid61** [comment]
I think maybe Boolean should be able to detect the missing phrase and construct a simple fallback radio list.

**Comment by phluid61** [comment]
Here's a possible patch. I don't have time to set up a proper pull request before the weekend:

```patch
diff --git a/lib/lang/en/phrases/system.xml b/lib/lang/en/phrases/system.xml
index aea9156..96776a0 100644
--- a/lib/lang/en/phrases/system.xml
+++ b/lib/lang/en/phrases/system.xml
@@ -1531,6 +1531,11 @@ For more information see <a href="http://eprints.org/d/?keyword=MetaFields">Meta
        <!-- 000x392 -->
        <epp:phrase id="lib/metafield/pagerange:other"><epc:pin name="pagerange"/></epp:phrase>
 
+       <epp:phrase id="lib/metafield/boolean:default_radio_list">
+               <label><epc:pin name="true"/> true</label><br/>
+               <label><epc:pin name="false"/> false</label><br/>
+       </epp:phrase>
+
 <!-- Search (used to be SearchExpression) -->
 
     <epp:phrase id="lib/searchexpression:simple_link" ref="cgi/search:simple_search" />
diff --git a/perl_lib/EPrints/MetaField/Boolean.pm b/perl_lib/EPrints/MetaField/Boolean.pm
index 05820cc..6f7682a 100644
--- a/perl_lib/EPrints/MetaField/Boolean.pm
+++ b/perl_lib/EPrints/MetaField/Boolean.pm
@@ -119,9 +119,14 @@ FALSE=> $session->phrase( $self->{confid}."_fieldopt_".$self->{name}."_FALSE"),
                        id => "${basename}_FALSE",
                        value => "FALSE" );
                my $f = $session->make_doc_fragment;
+               my $phrase_id = $self->{config}."_radio_".$self->{name};
+               if( !$session->get_lang->has_phrase( $phrase_id ) )
+               {
+                       $phrase_id = "lib/metafield/boolean:default_radio_list";
+               }
                $f->appendChild( 
                        $session->html_phrase(
-                               $self->{confid}."_radio_".$self->{name},
+                               $phrase_id,
                                true=>$true,
                                false=>$false ) );
                if( !$self->get_property( "required" ) )
```

**Comment by phluid61** [comment]
(It still potentially generates HTML IDs for the \<input> elements that aren't compatible with HTML 4.01, as the `confid` can begin with a digit. If we're only targeting HTML 5+ there's no problem)

**Comment by mpbraendle** [comment]
We do have an extended BatchEdit plugin that allows to do Find and Replace on author names and other multi-value fields without changing their positions - I will provide it on eprintsug GitHub.
Also, we had some problems with UUIDs being displayed instead of field names.
