### ISSUE TITLE
DOI Import Plugin Bug following Crossref website updates.

### ISSUE THREAD

**Issue by wfyson** [eprints/eprints#439]
Following a series of updates to the Crossref site, the DOI import plugin no longer works. The base URL used by the plugin returns a 301 "moved permanently"  response.

**Comment by wfyson** [comment]
Fixed by updating the URL from http://www.crossref.org/openurl to http://doi.crossref.org/openurl. 

https://github.com/eprints/eprints/commit/24de2fc05604aa7f0d34677ed2eb470e4f425a9d

**Comment by phluid61** [comment]
Should we switch this up to https while it's being updated?

**Comment by phluid61** [comment]
Never mind, crossref hasn't enabled it. :disappointed:
