### ISSUE TITLE
What perl version eprints 3.3.15 and 3.4 supports?

### ISSUE THREAD

**Issue by Izoniz** [eprints/eprints#444]
I'm trying to install eprints on system with perl 5.24. It shows many errors. 
Somewhere I found info that eprints work on perl 5.18. The oldest version what I have in ports 5.20. 
Can it work on 5.20?

**Comment by phluid61** [comment]
We're currently upgrading our server infrastructure, and the new machine is running "perl 5, version 24, subversion 0 (v5.24.0) built for x86_64-linux-thread-multi" (also Apache/2.4.18)

There were some version-related issues that we squished in the migration process, but I can't remember what they were. Mostly warnings about changes to edgy things like `~~`. Our codebase is a mess, though, having grown organically for many many years, roughly in parallel with the core.

**Comment by Izoniz** [comment]
Do you mean eprints work on perl 5.24?

**Comment by phluid61** [comment]
I mean: QUT's fork of EPrints is running on a DEV server under perl 5.24.

**Comment by Izoniz** [comment]
Ah, where can I gat this QUT's fork of EPrints? Can I import my archive from erpints to it?

**Comment by phluid61** [comment]
I'm afraid you can't get the QUT fork. It's a horrible mess, and has a lot of changes very specific to our needs. From time to time we bundle relevant and useful changes we've made and push them up-stream to the core.

Regarding that regex issue, yeah I remember that one. This was my workaround (which is still going through QA):

~~~diff
diff --git a/perl_lib/URI/Escape.pm b/perl_lib/URI/Escape.pm
index e09d76a..e6e7569 100644
--- a/perl_lib/URI/Escape.pm
+++ b/perl_lib/URI/Escape.pm
@@ -202,7 +202,8 @@ sub uri_unescape {
 }
 
 sub escape_char {
-    return join '', @URI::Escape::escapes{$_[0] =~ /(\C)/g};
+    use bytes;
+    return join '', @URI::Escape::escapes{$_[0] =~ /(.)/g};
 }
 
 1;
~~~

**Comment by phluid61** [comment]
(I may be changing that regexp, either by adding `/s`, or replacing the `.` with something else.)

**Comment by denics** [comment]
this is related to #423. Instead of changing the line you can directly remove the URI library and use the system one.

**Comment by Izoniz** [comment]
Thanks for your help! I made this change in file perl_lib/URI/Escape.pm and eprints works!
Just testing for all functionality...

In log see this:
CGI::param called in list context from /eprints3/perl_lib/EPrints/Repository.pm line 397, this can lead to vulnerabilities.
 See the warning in "Fetching the value or values of a single named parameter" at /usr/local/lib/perl5/site_perl/CGI.pm line 412.

Is it ok?

**Comment by denics** [comment]
Hi @Izoniz, this last question has been answered #415

**Comment by denics** [comment]
@jiadiyao can you close this issue please?
