### ISSUE TITLE
Subject in view lost / doesn't show

### ISSUE THREAD

**Issue by prasasti** [eprints/eprints#480]
i heave 2 server for repositories, the one who used for test running normal.
but the real server, when i check for subject repository.com/view/subjects/
the subjects list not show up.
and i check in folder html/en/view/subjects still 13.956 files on it.
but when i checked index.page just show this code <div class="ep_view_menu"></div>

when i try to copy paste idex.page from server for test. after regenerate views back to 
<div class="ep_view_menu"></div>
can someone help me. i dont know what happen

**Comment by mpbraendle** [comment]
Please ask your question in the ep-tech mail list where there are many people who can help you - this page here is for submitting bugs.
