### ISSUE TITLE
BibTeX Parser should be updated to newest version

### ISSUE THREAD

**Issue by mpbraendle** [eprints/eprints#482]
EPrints 3.3 still uses BibTeX::Parser 0.63 in perl_lib/BibTeX . Should be updated to newest version (1.01).

**Comment by mpbraendle** [comment]
Thank you phluid61.

There is also dependency to LaTeX::ToUnicode that must be resolved so that the code works.

Also, $self->{fh}->eof (line 47) and $self->{fh}->getline (lines 51, 68) did not work on our system, had to be replaced with the original lines from BibTeX::Parser 0.63

**Comment by drn05r** [comment]
I do not think there is any easy way round needing the LaTeX::toUncode, so I will add that to GitHub along with the modifications to the latest version of BibTeX::Parser to make it work for @mpbraendle and me (on my CentOS 7 test server).
