### ISSUE TITLE
Only show current version of package in bazaar

### ISSUE THREAD

**Issue by goetzk** [eprints/eprints#490]
Hi,
I've been looking at plugins for DataCiteDOI , searching both bazaar.eprints and via the EPrints Bazaar page in my repository admin screen.

http://bazaar.eprints.org/cgi/search/simple?q=DataCite
http://bazaar.eprints.org/cgi/search/simple?q=Cite

It results in prints 545 (2.0.1) and 380 (1.0.0) being displayed, despite the 1.0.0 version clearly being replaced by 2.0.1. It would be great if the bazaar (especially the version embedded in eprints) would hide old versions by default and only show them when requested.

Print 439 appears to be a repackaging, I'm not sure if this should be able to be superseded/hidden by the original uploader but probably not (to avoid fights).

Karl.

**Comment by drn05r** [comment]
Based on using the two links you provided, I can see that 439 has the EPMID DataCiteDoi-dev whereas 1100 (now the latest version of the proper plugin) has EPMID DataCiteDoi.  Therefore, I have retired 439 as I agree this is confusing.  The Bazaar does have the odd few duplicate plugins or other broken/incomplete plugins.  We are hoping to put together an effort to tidy a lot of this up.

**Comment by goetzk** [comment]
thanks!
