### ISSUE TITLE
Thumbnail generation broken "convert: not authorized"

### ISSUE THREAD

**Issue by tgoeg** [eprints/eprints#496]
If thumbnails do not get generated correctly, a wrong ImageMagick policy may be at fault. When running
```
~/bin/epadmin redo_thumbnails <archive>
```
the following errors show:
```
convert: not authorized `/opt/eprints3/archives/<archive>/documents/disk0/00/00/01/75/01/file.pdf' @ error/constitute.c/ReadImage/412.
convert: no images defined `JPEG:/tmp/UmeHxI2skp/medium.jpg' @ error/convert.c/ConvertImageCommand/3258.
```

Please make the error show up somewhere noticeable, add this hint to the wiki, check the permissions before actually attempting to convert, etc.

The solution looks like this:
```
--- /etc/ImageMagick-6/policy.xml.bak	2018-11-21 14:22:41.393253192 +0100
+++ /etc/ImageMagick-6/policy.xml	2018-11-21 14:22:49.561253192 +0100
@@ -73,6 +73,6 @@
   <!-- disable ghostscript format types -->
   <policy domain="coder" rights="none" pattern="PS" />
   <policy domain="coder" rights="none" pattern="EPI" />
-  <policy domain="coder" rights="none" pattern="PDF" />
+  <policy domain="coder" rights="read" pattern="PDF" />
   <policy domain="coder" rights="none" pattern="XPS" />
 </policymap>
```

**Comment by photomedia** [comment]
I had this same issue on Ubuntu 18.04, and this fixed it.

**Comment by tgoeg** [comment]
I don't know what eprints does with ImageMagick and PDFs. If it ever tries to write PDFs with ImageMagick, "read|write" will be necessary. For generating thumbnails alone, "read" is enough.

On 05.02.19 21:32, Tomasz Neugebauer wrote:

Is rights="read" sufficient, or should it be rights="read|write" ?

**Comment by drn05r** [comment]
This is an ImageMagick rather than EPrints issue and the discussion above provides the solution to fixe the ImageMagick config, so this issue can be closed.
