### ISSUE TITLE
EPrints System Error

### ISSUE THREAD

**Issue by hrace009** [eprints/eprints#499]
I have installed ePrints, when i hit browse, i got message with white scree:
<pre><code>EPrints System Error
Can't open to write to file: /usr/share/eprints/archives/REPOID/html/en/view/subjects/index.html</code></pre>

Any solution or information about this?

**Comment by jesusbagpuss** [comment]
This sounds like a permissions issue. 

I think the instructions here:
https://wiki.eprints.org/w/Installing_EPrints_on_RHEL/Fedora/CentOS#Using_SELinux
miss out the directory [eprintspath]/archives/[repoid]/html/ e.g.
`chcon -R -h -t httpd_sys_script_rw_t eprintspath]/archives/[repoid]/html/`

The browse pages can be generated in two ways:
via the command line:
`[eprintspath]/bin/generate_views REPOID`
or, they will get automatically created (and/or updated) when you visit the URL (as you did).

Also, it might be worth joining the EPrints tech mailing list:
https://wiki.eprints.org/w/Contact#eprints-tech_Mailing_List
there are more people on that list who may be able to help get you started!

Cheers,
John

**Comment by hrace009** [comment]
ohhh okay, thank for the information, yes i forgot about SELINUX.
