### ISSUE TITLE
eprint->get_url never renders https

### ISSUE THREAD

**Issue by dennmuel** [eprints/eprints#507]
Hi everyone,

not sure if we have a configuration problem or if this is a bug...

We've set up our instance to use https just fine. However, URLs rendered by eprint->get_url are always in http. Could it be, that there are some places left, where https must be made the preferred option (and not http) as you did [here](https://github.com/eprints/eprints/commit/95103e40afae535f151a87f5856cb1040a485bd3)?

I found some lines in Repository.pm where I think it should be changed [like this](https://github.com/dennmuel/eprints/commit/ce49394c6b647b8b20827c2e6c71957ea2bbc643) (untested, just sketching it out).

Best regards
Dennis

**Comment by drn05r** [comment]
Hi Dennis,

I have been trying to simplify the setup for http or https in EPrints 3.4.  Basically I wanted to support three different setups:

1. HTTP only - Really just for developers who do not want to faff around with certificates on repositories that are not publicly accessible.

2. HTTPS for backend only: This is what the default is currently.  All pages are accessible over HTTPS but you will only be forced to go to the HTTPS ones for pages where you need to be logged in (and the login page itself).

3. HTTPS everywhere: This is where every page (inc. images, CSS, JavaScript) is HTTPS.  Requests for HTTP will be redirected to HTTPS automatically.  It is recommended you also enable HSTS in securevhost.conf.

I have some instructions that I should now put on wiki.eprints.org for this as there is now a release for 3.4 that has this simplified configuration for 10_core.pl.  I will see if it can be ported back to 3.3.  I was however a little concerned about how this might affect people upgrading if they have a 10_core.pl that is non-standard.

Regards

David Newman

**Comment by dennmuel** [comment]
Hi David,

thank you very much for your answer. The config backport would be very nice. We have no plans to upgrade to 3.4 at the moment so this would benifit us for now.

Best regards
Dennis

**Comment by dennmuel** [comment]
Managed to get it right following [this wiki page](https://wiki.eprints.org/w/HTTPS-only_and_HSTS#Changes_to_archive.27s_cfg.d.2F10_core.pl).
