### ISSUE TITLE
Bug in Tokenizer

### ISSUE THREAD

**Issue by mpbraendle** [eprints/eprints#514]
https://github.com/eprints/eprints/blob/a06535633bfb8d79a3891d48f4c8668ca33a6173/perl_lib/EPrints/Index/Tokenizer.pm#L91

is $utext defined at this point?

**Comment by jesusbagpuss** [comment]
Not by the looks of things!
I think it's a typo in the method definition. The POD suggests that...
https://github.com/eprints/eprints/blob/a06535633bfb8d79a3891d48f4c8668ca33a6173/perl_lib/EPrints/Index/Tokenizer.pm#L76

**Comment by phluid61** [comment]
Looks like lines 89 and 101 should be `s/text/utext/`.

How often is a `Unicode::String` actually passed in? And how often is one with `stringify_as != 'utf8'`? Seems pretty niche to me.

**Comment by denics** [comment]
not really if you have a greek repository.

**Comment by phluid61** [comment]
I don't understand. Greek commonly uses ISO 8859-7 or Unicode character sets, no? Both of which fit perfectly fine in regular Perl strings.

So why would a Greek repository be producing `Unicode::String` objects, let alone `Unicode::String` objects not set to stringify as utf-8?
