### ISSUE TITLE
Can't access login and register page

### ISSUE THREAD

**Issue by syaifulrmdhn** [eprints/eprints#517]
After set HTTPS configuration, i can't access access login and register page. The url can't render well to https, how to solve this?

**Comment by drn05r** [comment]
Have you run `bin/generate_apacheconf --system --replace` and reloaded your webserver (e.g. `apachectl graceful`).  

If you have problems like this you are better joining the EPrints tech list to ask:

http://mailman.ecs.soton.ac.uk/mailman/listinfo/eprints-tech

GitHub issue are really intended to report for bugs in the code, which I don't this is.

**Comment by syaifulrmdhn** [comment]
I was run bin/generate_apacheconf --system --replace and reloaded webserver, but still not work. I can't acces another page, except login and register. The error like this
![photo_2021-07-09_10-03-39](https://user-images.githubusercontent.com/24586705/125017494-79083380-e09d-11eb-95ea-606fcf314c57.jpg)
