### ISSUE TITLE
Google Scholar results without abstracts

### ISSUE THREAD

**Issue by dennmuel** [eprints/eprints#519]
Hi,

more of a question, less of an issue...

We noticed that eprints without abstract show navigation items in the descriptions of Google Scholar search results:
![image](https://user-images.githubusercontent.com/21078769/167393811-fe76e432-eada-4e55-a777-5dcdf09a2c67.png)

In the example, the first entry shows the abstract, the second shows the title followed by strings from the navigation menu (website, imprint, privacy policy etc... Sorry, it's only in German). The same seems to apply to other instances of EPrints (I've checked with two others).

Is there anything that can be done about this on the side of EPrints? Or is it just flawed indexing on Google Scholar's side?

Cheers!

**Comment by jesusbagpuss** [comment]
Hi @dennmuel ,
It might be worth updating the navigation items on the pages to use semantic tags e.g.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav 
to see if that helps at all?

This might also be useful - but doesn't directly mention what the default is https://developers.google.com/search/docs/advanced/appearance/snippet

**Comment by jesusbagpuss** [comment]
NB The EPrints 3.4 default template might be useful as a reference: https://github.com/eprints/eprints3.4/blob/master/lib/templates/default.xml 
- see `<header>`, `<footer>` and `<nav>` elements.

**Comment by dennmuel** [comment]
Thanks for the quick reply,  @jesusbagpuss! I'll give it a try and have my colleague check the results.
