### ISSUE TITLE
Shipping the OAI XSLT with another library?

### ISSUE THREAD

**Issue by poikilotherm** [eprints/eprints#521]
Hi there!

Zenodo inspired me to add your great OAI XSLT https://github.com/eprints/eprints/blob/3.3/lib/static/oai2.xsl to https://github.com/gdcc/xoai, which is the base of the OAI-PMH endpoint of https://github.com/IQSS/dataverse. ([see also](https://github.com/gdcc/xoai/issues/15))

XOAI is a BSD 3-clause licensed library, so should be compatible with your GPL-3.0 license (and not become "infected"), especially as we are not linking the lib or changing the XSLT content still carrying your copyright etc. (Note: pre-commit fixed some whitespace issues)

If you think we should not do this, please reach out. Thank you for your great work!

**Comment by jesusbagpuss** [comment]
Hi @poikilotherm,
Thanks for asking the question.

The same XSLT is also part of a newer release of EPrints: https://github.com/eprints/eprints3.4/blob/master/lib/static/oai2.xsl which has a different licence (Lesser General Public License version 3). You might want to include that version as your starting point (although I don't think it matters!).

@drn05r  - I guess this should have an official answer from 'EPrints'?
I've emailed Chris G. about this as I've seen the XSLT in use on other platforms previously.

**Comment by poikilotherm** [comment]
Thanks @jesusbagpuss for your nice reply and pointing me towards the LGPL version, that's perfect from the IP law perspective!

I guess this can be closed as "Go ahead" then.

EDIT: I replaced the commit with the LGPL version to avoid any spoiled beans. I'll leave this in the open PR for another day before going ahead to merge it.

**Comment by poikilotherm** [comment]
Thanks again for your help @jesusbagpuss! I guess this can be closed.
