### ISSUE TITLE
Cannot Create User from cli and web

### ISSUE THREAD

**Issue by erwan690** [eprints/eprints#524]
hi after move to new server i can't  create user

```
bash-4.2$ ./bin/epadmin --version
epadmin 3.3.16 [Schema 3.3.4]
```

```
bash-4.2$ ./bin/epadmin test myrepo
Use of uninitialized value in concatenation (.) or string at (eval 127) line 34.
Everything seems OK.
```

```
bash-4.2$ ./bin/epadmin create_user myrepo
Use of uninitialized value in concatenation (.) or string at (eval 127) line 34.
Creating a new user in digilib

Enter a username [admin] ? admin2
Select a user type (user|editor|admin) [admin] ? admin
Enter Password? 
Email? admin@myrepo.mail
Can't call method "update_triggers" on an undefined value at /usr/share/eprints/bin/../perl_lib/EPrints/DataObj/User.pm line 302, <STDIN> line 4.
```

if i create from web create user i get 500 internal server erro and log in error_log
`Can't call method "update_triggers" on an undefined value at /usr/share/eprints/bin/../perl_lib/EPrints/DataObj/User.pm line 302,
`
i have google this and get : this](https://www.eprints.org/eptech/msg05046.html
)

on this forum he played with right but i don't know how to make it works

thanks you

**Comment by jesusbagpuss** [comment]
Hi @erwan690,
If you run:
` bin/epadmin update_dry_run digilib`
does it tell you anything? 

The section that is triggering the error is:
https://github.com/eprints/eprints/blob/93bd42f9f30561e88df9b72e759dc14997a22e17/perl_lib/EPrints/DataObj/User.pm#L296-L302

The 'undefined value' means that the `$new_user` is not set, so something is going wrong with the `SUPER::create_from_data()` call.
The parent (SUPER) class of `EPrint::DataObj::User` is `EPrint::DataObj` (from https://github.com/eprints/eprints/blob/93bd42f9f30561e88df9b72e759dc14997a22e17/perl_lib/EPrints/DataObj/User.pm#L119).

The failing method is this:
https://github.com/eprints/eprints/blob/93bd42f9f30561e88df9b72e759dc14997a22e17/perl_lib/EPrints/DataObj.pm#L239-L352

There are a few things that could be causing it to fail, but a first guess is that there is a missing column in the user database table. The `update_dry_run` should show this.

If it does say there are missing fields, you can try:
` bin/epadmin update digilib`
but I'd advise making sure you have a backup of the database before running this.

**Comment by erwan690** [comment]
hi @jesusbagpuss 

thanks for your advice

i have run 
`bin/epadmin update_dry_run digilib`

result 
```
Dry run: Fixed saved_search__rindex.field collation
Dry run: Fixed document__rindex.field collation
Dry run: Fixed user__rindex.field collation
Dry run: Fixed eprint__rindex.field collation
Dry run: Fixed request__rindex.field collation
Dry run: Fixed subject__rindex.field collation
Dry run: 0 datasets added
Dry run: 0 fields added
Dry run: 0 counters were added
```
 
if i have missing colomn maybe 1 field added right 

fixed on this result it's mean reconfigure ?

thanks you for any help

**Comment by jesusbagpuss** [comment]
Based on the above, I would run the:
`bin/epadmin update digilib`
command now to make the changes to the database, and then try creating a user via the CLI again.

**Comment by jesusbagpuss** [comment]
(sorry, didn't mean to close that - clicked the wrong button!)

**Comment by erwan690** [comment]
hi
i have run update 

```
bash-4.2$ ./bin/epadmin update digilib --verbose
Use of uninitialized value in concatenation (.) or string at (eval 127) line 34.

Starting EPrints Repository.
Connecting to DB ... done.
0 datasets added
0 fields added
0 counters were added
bash-4.2$ ./bin/epadmin create_user digilib
Use of uninitialized value in concatenation (.) or string at (eval 127) line 34.
Creating a new user in digilib
Enter a username [admin] ? erwan690
Select a user type (user|editor|admin) [admin] ? admin
Enter Password? 
Email? erwan690@myrepo.local
Can't call method "update_triggers" on an undefined value at /usr/share/eprints/bin/../perl_lib/EPrints/DataObj/User.pm line 302, <STDIN> line 4.

```

but it still  same 

thanks for your any help

**Comment by jesusbagpuss** [comment]
Do other parts of the system work OK (can you log in , create an EPrint)?

If you run this, does it tell you anything extra?
`./bin/epadmin create_user digilib --verbose --verbose`

Do these two queries result in the same number?
`SELECT MAX(userid) FROM user;`
`SELECT counter FROM counters WHERE countername = 'userid';`

**Comment by erwan690** [comment]
wow yes thats the problem ..

counter in autoincrement on table user is different on counter table 

thanks you very much @jesusbagpuss
