### ISSUE TITLE
Issue related to page field

### ISSUE THREAD

**Issue by abidfakhrealam** [eprints/eprints#527]
My entry is not saving when I enter this value in the page field VX, 123 p.

when I check the error log file. It is showing this error:-

EPScript error: Script in Workflow (eprint,default): expected closing method bracket (found STRING) at character 51
type.one_of('book_section', 'book_review' 'article', 'conference_item')
                                                   ^ here at /usr/share/eprints/perl_lib/EPrints/Script.pm line 162.

DBD::mysql::st execute failed: Incorrect integer value: 'XV, 237' for column 'pages' at row 1 at /usr/share/eprints/perl_lib/EPrints/Database.pm line 1187.
UPDATE `eprint` SET `isbn`=?, `pages`=?, `edit_lock_until`=?, `official_url`=?, `lastmod_year`=?, `lastmod_month`=?, `lastmod_day`=?, `lastmod_hour`=?, `lastmod_minute`=?, `lastmod_second`=? WHERE `eprintid`='6532': 1366 at /usr/share/eprints/perl_lib/EPrints/Database.pm line 1595.
	EPrints::Database::update(EPrints::Database::mysql=HASH(0x7f13b30f92b0), EPrints::DataSet=HASH(0x7f13b1eed050), HASH(0x7f13a8043a50), HASH(0x7f13a8057c28)) called at /usr/share/eprints/perl_lib/EPrints/DataObj.pm line 743
	EPrints::DataObj::commit(EPrints::DataObj::EPrint=HASH(0x7f13a8057c70), undef) called at /usr/share/eprints/perl_lib/EPrints/DataObj/EPrint.pm line 1031
	EPrints::DataObj::EPrint::commit(EPrints::DataObj::EPrint=HASH(0x7f13a8057c70)) called at /usr/share/eprints/perl_lib/EPrints/Workflow/Stage.pm line 221
	EPrints::Workflow::Stage::update_from_form(EPrints::Workflow::Stage=HASH(0x7f13a80a4a80), EPrints::ScreenProcessor=HASH(0x7f13b1d9c4a8)) called at /usr/share/eprints/perl_lib/EPrints/Workflow.pm line 401
	EPrints::Workflow::update_from_form(EPrints::Workflow=HASH(0x7f13a80a4048), EPrints::ScreenProcessor=HASH(0x7f13b1d9c4a8)) called at /usr/share/eprints/perl_lib/EPrints/Plugin/Screen/EPrint/Edit.pm line 189
	EPrints::Plugin::Screen::EPrint::Edit::action_next(EPrints::Plugin::Screen::EPrint::Edit=HASH(0x7f13a8057fa0)) called at /usr/share/eprints/perl_lib/EPrints/Plugin/Screen.pm line 240
	EPrints::Plugin::Screen::from(EPrints::Plugin::Screen::EPrint::Edit=HASH(0x7f13a8057fa0)) called at /usr/share/eprints/perl_lib/EPrints/Plugin/Screen/EPrint/Edit.pm line 117
	EPrints::Plugin::Screen::EPrint::Edit::from(EPrints::Plugin::Screen::EPrint::Edit=HASH(0x7f13a8057fa0)) called at /usr/share/eprints/perl_lib/EPrints/ScreenProcessor.pm line 353
	EPrints::ScreenProcessor::process("EPrints::ScreenProcessor", "session", EPrints::Repository=HASH(0x7f13b01f3d88), "template", undef, "url", "/cgi/users/home") called at /usr/share/eprints/cgi/users/home line 43
	ModPerl::ROOT::ModPerl::Registry::usr_share_eprints_cgi_users_home::handler(Apache2::RequestRec=SCALAR(0x7f13b1e23a60)) called at /usr/lib/x86_64-linux-gnu/perl5/5.34/ModPerl/RegistryCooker.pm line 207
	eval {...} called at /usr/lib/x86_64-linux-gnu/perl5/5.34/ModPerl/RegistryCooker.pm line 207
	ModPerl::RegistryCooker::run(ModPerl::Registry=HASH(0x7f13b1db3ec0)) called at /usr/lib/x86_64-linux-gnu/perl5/5.34/ModPerl/RegistryCooker.pm line 173
	ModPerl::RegistryCooker::default_handler(ModPerl::Registry=HASH(0x7f13b1db3ec0)) called at /usr/lib/x86_64-linux-gnu/perl5/5.34/ModPerl/Registry.pm line 32
	ModPerl::Registry::handler("ModPerl::Registry", Apache2::RequestRec=SCALAR(0x7f13b1e23a60)) called at -e line 0
	eval {...} called at -e line 0

Argument "XV, 237" isn't numeric in sprintf at /usr/share/eprints/perl_lib/EPrints/MetaField/Int.pm line 70.
Error committing eprint.6532:

**Comment by drn05r** [comment]
The issue is you have the line:
`type.one_of('book_section', 'book_review' 'article', 'conference_item')`
On this line there is no comma between `book_review` and `article`.  You should change it to:
`type.one_of('book_section', 'book_review', 'article', 'conference_item')`
