### ISSUE TITLE
Internal Server Error Simple Search Eprints 3.4.4

### ISSUE THREAD

**Issue by desawarna** [eprints/eprints#528]
I'm using eprint 3.4.4 ,
Ubuntu 22.04-86_64 ,
Perl 5.34.0 ,
Mysql 8.0.35-0ubuntu0.22.04.1
Let's Encrypt
Apache 2.4.52 

When using Eprints simple search, an error message appears in the search results

```
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Apache/2.4.52 (Ubuntu) Server at repository.desawarna.ac.id Port 443
```

how to solve it?

Thank you friends 😄

**Comment by jesusbagpuss** [comment]
Hi,
Are there any additional details in the Apache error log (might be here: `/var/log/apache2/error.log` for Ubuntu)?
This should provide more details about what caused the issue and help us resolve it.

It's worth asking about this type of issue on the EPrints Tech list. Details can be found here:
https://wiki.eprints.org/w/Eprints-tech_Mailing_List

One last note - this is the EPrints v3.3 github repository. The EPrints 3.4 repository (the version you are using) is here:
https://github.com/eprints/eprints3.4/

I suspect the error is just a configuration issue - which I will try and help you resolve here.

**Comment by desawarna** [comment]
@jesusbagpuss , this is eror log /var/log/apache2/error.log

```
[Wed Aug 14 00:00:02.850790 2024] [perl:notice] [pid 9332:tid 140149100697472] Warning! Running EPrints under threads is experimental and liable to break
[Wed Aug 14 00:00:03.368622 2024] [perl:notice] [pid 9332:tid 140149100697472] EPrints archives loaded: repository_asik
[Wed Aug 14 00:00:03.821628 2024] [mpm_event:notice] [pid 9332:tid 140149100697472] AH00489: Apache/2.4.52 (Ubuntu) OpenSSL/3.0.2 mod_perl/2.0.12 Perl/v5.34.0 configured -- resuming normal operations
[Wed Aug 14 00:00:03.821653 2024] [core:notice] [pid 9332:tid 140149100697472] AH00094: Command line: '/usr/sbin/apache2'
[Wed Aug 14 03:07:51.630349 2024] [core:error] [pid 82435:tid 140149065975360] [client 103.173.227.187:40524] AH10244: invalid URI path (/cgi-bin/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/bin/sh)
[Wed Aug 14 03:07:52.332132 2024] [core:error] [pid 82435:tid 140148935222848] [client 103.173.227.187:40540] AH10244: invalid URI path (/cgi-bin/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/bin/sh)
[Wed Aug 14 03:31:22.711647 2024] [core:error] [pid 82435:tid 140148314457664] [client 104.248.194.114:50670] AH10244: invalid URI path (/cgi-bin/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/bin/sh)
[Wed Aug 14 03:31:26.137565 2024] [core:error] [pid 82434:tid 140148784219712] [client 104.248.194.114:57556] AH10244: invalid URI path (/cgi-bin/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/bin/sh)
[Wed Aug 14 07:38:40.005854 2024] [core:error] [pid 82434:tid 140148943615552] [client 128.199.225.7:40904] AH10244: invalid URI path (/cgi-bin/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/bin/sh)
[Wed Aug 14 07:38:40.199510 2024] [core:error] [pid 82434:tid 140148935222848] [client 128.199.225.7:41056] AH10244: invalid URI path (/cgi-bin/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/%%32%65%%32%65/bin/sh)
```

**Comment by jesusbagpuss** [comment]
Hi @desawarna ,
I don't think those lines from the error log relate to the search issue, as EPrints does not use `cgi-bin` - it uses `cgi`.

You could try this:
- on the server, run `tail -f /var/log/apache2/error.log` - this should display the last lines of that file, and also show any new ones added.
- visit the search page, and cause the error to happen
- have a look back on the server - you should be able to see some new lines, with the details of what caused the issue.
- to stop the `tail` command, press Ctrl+C.

If the above doesn't show anything, are there any other error logs in the apache2 folder?
Apache might be configured to have different log files for each vhost.
